# opane_set_app_icon(<target> <image>)
#
# Gives a program an icon of its own instead of the system's default:
#
#   opane_set_app_icon(my_game art/icon.png)
#
# <image> is a PNG, JPEG, BMP, TGA, GIF, or PSD, ideally square and at least
# 256 pixels across, or 1024 for a macOS app bundle. One that is not
# square is centred on a transparent square. A ready-made .ico (Windows) or
# .icns (macOS) is used as it is. The image may be one the build makes, as the
# output of an add_custom_command in the same directory.
#
#   Windows  the .exe carries the icon, in every size from 16 to 256 pixels:
#            File Explorer, the taskbar, Alt+Tab, and the window's title bar
#            all show it, because SDL gives its windows the .exe's icon
#   macOS    an app bundle (add_executable(... MACOSX_BUNDLE ...)) carries it
#            as its .icns; the window uses it too
#   Linux    an executable file has no icon, so the window shows it: the
#            picture is embedded, and the window opane opens takes it
#
# AppConfig::Icon, or App::SetIcon, overrides the window's icon while the
# program runs, on every platform.

set(OPANE_APP_ICON_EMBED_SCRIPT "${CMAKE_CURRENT_LIST_DIR}/EmbedBinary.cmake")

function(opane_set_app_icon Target Image)
    get_filename_component(ImagePath "${Image}" ABSOLUTE)
    get_source_file_property(Generated "${ImagePath}" GENERATED)
    if(NOT EXISTS "${ImagePath}" AND NOT Generated)
        message(FATAL_ERROR "opane_set_app_icon(${Target} ${Image}): there is no such file, and nothing in "
                            "this directory makes it.")
    endif()
    get_filename_component(Extension "${ImagePath}" LAST_EXT)
    string(TOLOWER "${Extension}" Extension)
    set(ReadyMade FALSE)
    if(Extension STREQUAL ".ico" OR Extension STREQUAL ".icns")
        set(ReadyMade TRUE)
    endif()

    # The converter: built from source beside opane, installed beside an
    # installed opane. Only needed when the icon is made from a picture.
    # Naming the tool as the command builds it first; depending on it as well
    # remakes the icon when the tool changes, which only a tool built here can.
    set(Tool "")
    set(ToolDepends "")
    if(TARGET opane_icon)
        set(Tool opane_icon)
        set(ToolDepends opane_icon)
    elseif(TARGET opane::opane_icon)
        set(Tool opane::opane_icon)
    elseif(NOT ReadyMade)
        message(FATAL_ERROR "opane_set_app_icon: the opane_icon tool is missing from this opane package, so "
                            "${Image} cannot be converted. Pass a ready-made .ico or .icns instead.")
    endif()

    set(Directory "${CMAKE_CURRENT_BINARY_DIR}/opane_icon/${Target}")

    if(WIN32)
        if(Extension STREQUAL ".icns")
            message(FATAL_ERROR "opane_set_app_icon: ${Image} is a macOS icon; Windows needs a .ico or a picture.")
        endif()
        if(Extension STREQUAL ".ico")
            set(IcoPath "${ImagePath}")
        else()
            set(IcoPath "${Directory}/icon.ico")
            add_custom_command(
                OUTPUT "${IcoPath}"
                COMMAND ${CMAKE_COMMAND} -E make_directory "${Directory}"
                COMMAND ${Tool} "${ImagePath}" "${IcoPath}"
                DEPENDS "${ImagePath}" ${ToolDepends}
                COMMENT "Making the icon for ${Target} from ${Image}"
                VERBATIM)
        endif()

        # Resource 1 is the first icon group, which is the one Explorer shows
        # and the one SDL gives the window. The script is copied into place
        # whenever the icon changes, because the resource compiler does not
        # notice a changed file it only names.
        file(WRITE "${Directory}/icon.rc.in"
            "// Generated by opane_set_app_icon. Do not edit.\n"
            "1 ICON \"${IcoPath}\"\n")
        add_custom_command(
            OUTPUT "${Directory}/icon.rc"
            COMMAND ${CMAKE_COMMAND} -E copy "${Directory}/icon.rc.in" "${Directory}/icon.rc"
            DEPENDS "${Directory}/icon.rc.in" "${IcoPath}"
            VERBATIM)
        target_sources(${Target} PRIVATE "${Directory}/icon.rc")
        return()
    endif()

    if(APPLE)
        get_target_property(IsBundle ${Target} MACOSX_BUNDLE)
        if(IsBundle)
            if(Extension STREQUAL ".icns")
                set(IcnsPath "${ImagePath}")
            elseif(Extension STREQUAL ".ico")
                message(FATAL_ERROR "opane_set_app_icon: ${Image} is a Windows icon; macOS needs a .icns or a picture.")
            else()
                set(IcnsPath "${Directory}/icon.icns")
                add_custom_command(
                    OUTPUT "${IcnsPath}"
                    COMMAND ${CMAKE_COMMAND} -E make_directory "${Directory}"
                    COMMAND ${Tool} "${ImagePath}" "${IcnsPath}"
                    DEPENDS "${ImagePath}" ${ToolDepends}
                    COMMENT "Making the icon for ${Target} from ${Image}"
                    VERBATIM)
            endif()
            get_filename_component(IcnsName "${IcnsPath}" NAME)
            set_source_files_properties("${IcnsPath}" PROPERTIES MACOSX_PACKAGE_LOCATION Resources)
            target_sources(${Target} PRIVATE "${IcnsPath}")
            set_target_properties(${Target} PROPERTIES MACOSX_BUNDLE_ICON_FILE "${IcnsName}")
        endif()
    endif()

    # The window's icon, embedded: a 256-pixel square the program's window
    # takes when it opens. A ready-made icon file is not something opane can
    # read, so it is not embedded; a bundle's window shows the bundle's icon.
    if(ReadyMade)
        return()
    endif()

    set(PngPath "${Directory}/window_icon.png")
    set(ImageSource "${Directory}/window_icon.cpp")
    set(Registration "${Directory}/window_icon_register.cpp")
    add_custom_command(
        OUTPUT "${PngPath}"
        COMMAND ${CMAKE_COMMAND} -E make_directory "${Directory}"
        COMMAND ${Tool} "${ImagePath}" "${PngPath}"
        DEPENDS "${ImagePath}" ${ToolDepends}
        COMMENT "Making the window icon for ${Target} from ${Image}"
        VERBATIM)
    add_custom_command(
        OUTPUT "${ImageSource}"
        COMMAND ${CMAKE_COMMAND}
                -DINPUT=${PngPath}
                -DOUTPUT=${ImageSource}
                -DSYMBOL=OpaneAppIconPng
                -P "${OPANE_APP_ICON_EMBED_SCRIPT}"
        DEPENDS "${PngPath}" "${OPANE_APP_ICON_EMBED_SCRIPT}"
        VERBATIM)

    # Hands the picture to opane before main runs; StartApp puts it on the
    # window.
    file(WRITE "${Registration}.in"
        "// Generated by opane_set_app_icon. Do not edit.\n"
        "\n"
        "#include <cstddef>\n"
        "\n"
        "extern const unsigned char OpaneAppIconPng[];\n"
        "extern const size_t OpaneAppIconPngSize;\n"
        "\n"
        "namespace opane::detail\n"
        "{\n"
        "void SetEmbeddedAppIcon(const unsigned char* png, size_t size);\n"
        "}\n"
        "\n"
        "namespace\n"
        "{\n"
        "[[maybe_unused]] const bool OpaneAppIconRegistered =\n"
        "    (opane::detail::SetEmbeddedAppIcon(OpaneAppIconPng, OpaneAppIconPngSize), true);\n"
        "}\n")
    configure_file("${Registration}.in" "${Registration}" COPYONLY)
    target_sources(${Target} PRIVATE "${ImageSource}" "${Registration}")
endfunction()
